# Generated by Django 4.0.4 on 2022-05-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0003_alter_organization_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='doshow',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='doshow',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='grade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
