# Generated by Django 4.0.4 on 2022-05-22 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0005_remove_stepcomment_course_course_listeners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specialization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specialization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
