# Generated by Django 4.0.4 on 2022-06-03 12:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_api', '0007_course_short_description_alter_course_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='coursereport',
            options={'verbose_name': 'Отзыв на курс', 'verbose_name_plural': 'Отзывы на курс'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='lessontype',
            options={'verbose_name': 'Тип урока', 'verbose_name_plural': 'Типы уроков'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': '    Организации'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': '   Специализации'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name': 'Шаг в уроке', 'verbose_name_plural': 'Шаги в уроке'},
        ),
        migrations.AlterModelOptions(
            name='stepcomment',
            options={'verbose_name': 'Комментарий на Шаг', 'verbose_name_plural': 'Комментарии на Шаг'},
        ),
        migrations.AlterModelOptions(
            name='tagforcourse',
            options={'verbose_name': 'Тег для курса', 'verbose_name_plural': 'Теги для курса'},
        ),
        migrations.AlterField(
            model_name='course',
            name='authors',
            field=models.ManyToManyField(related_name='own_courses', to=settings.AUTH_USER_MODEL, verbose_name='Учителя'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='doshow',
            field=models.BooleanField(blank=True, default=False, verbose_name='Показывать слушателям курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='listeners',
            field=models.ManyToManyField(related_name='undergoing_courses', to=settings.AUTH_USER_MODEL, verbose_name='Слушатели'),
        ),
        migrations.AlterField(
            model_name='course',
            name='order_in_specialization',
            field=models.SmallIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses_api.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses_api.specialization', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(related_name='courses', to='courses_api.tagforcourse', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
