# Generated by Django 4.0.5 on 2022-06-12 08:55

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_api', '0008_alter_course_options_alter_coursereport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='content',
        ),
        migrations.RemoveField(
            model_name='step',
            name='step_type',
        ),
        migrations.RemoveField(
            model_name='step',
            name='test',
        ),
        migrations.RemoveField(
            model_name='step',
            name='video',
        ),
        migrations.AddField(
            model_name='step',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='course',
            name='listeners',
            field=models.ManyToManyField(blank=True, related_name='undergoing_courses', to=settings.AUTH_USER_MODEL, verbose_name='Слушатели'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses_api.step')),
                ('content', ckeditor.fields.RichTextField(blank=True, default='', max_length=2048)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('courses_api.step',),
        ),
        migrations.CreateModel(
            name='TextLecture',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses_api.step')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', max_length=8192)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('courses_api.step',),
        ),
        migrations.CreateModel(
            name='VideoLecture',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses_api.step')),
                ('content', ckeditor.fields.RichTextField(blank=True, default='', max_length=2048)),
                ('video', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('courses_api.step',),
        ),
        migrations.CreateModel(
            name='VideoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', max_length=512)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('timing', models.TimeField()),
                ('grade', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('doshow', models.BooleanField(blank=True, default=False)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses_api.videolecture')),
            ],
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', max_length=512)),
                ('order', models.SmallIntegerField(default=0)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('grade', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('doshow', models.BooleanField(blank=True, default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses_api.test')),
            ],
        ),
    ]
