# Generated by Django 4.0.5 on 2022-06-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0009_remove_step_content_remove_step_step_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtask',
            old_name='answers',
            new_name='structure',
        ),
        migrations.RenameField(
            model_name='videoquestion',
            old_name='answers',
            new_name='structure',
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
