# Generated by Django 4.0.5 on 2022-06-16 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_api', '0010_rename_answers_testtask_structure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='authors',
        ),
        migrations.AddField(
            model_name='stepcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='courses_api.stepcomment'),
        ),
        migrations.CreateModel(
            name='AuthorsInCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=512)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_in_course', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_in_course', to='courses_api.course')),
            ],
        ),
    ]
